version: '3'
services:

  #Nginx Service
  webserver:
    image: nginx
    container_name: "po-sfr-server"
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8065:80"
    volumes:
      - ././:/var/www
      - /docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    networks:
      - po-sfr-network

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    container_name: "po-sfr-app"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: "remote_host=192.168.4.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    working_dir: /var/www
    volumes:
      - ././:/var/www
      - /docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - po-sfr-network

  #MySQL Service
  db:
    image: mysql:8.0.15
    container_name: "po-sfr-db"
    restart: unless-stopped
    command:
      --default-authentication-plugin=mysql_native_password
      --performance-schema --secure-file-priv=""
    ports:
      - "33064:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - po-sfr-db:/var/lib/mysql/
      - /docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - po-sfr-network

  #Docker Networks
networks:
  po-sfr-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/28
#Volumes
volumes:
  po-sfr-db:
    driver: local